services:
    cloudburst1:
        build:
            context: .
            network: host

        image: cloudburst1
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        environment:
            - AWS_REGION=us-west-2
            - BUCKET_NAME=dsgmd
            - MODE_STR=
            - LOCAL_MODE=0
            - WORK_ITEM=nc73619336
              # - TASKS_PATH=/opt/cloudburst/tasks-export.json
        volumes:
            - ~/.aws/credentials:/root/.aws/credentials:ro
