FROM ubuntu:18.04
# This is an image template for local testing, as well as fargate/ec2/lambda use

# configure timezone (optional)
RUN apt-get update --fix-missing && \
    DEBIAN_FRONTEND=noninteractive apt-get install tzdata
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN dpkg-reconfigure --frontend noninteractive tzdata

# include python3, 7zip packages, gfortran and gcc
RUN apt-get update --fix-missing && \
apt-get install -y curl apt-transport-https software-properties-common build-essential sudo nano bash python3 python3-pip gfortran gcc p7zip-full make cmake && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade boto3 jsonschema

# create and switch to a non-priviliged (but sudo-enabled) user, arbitrary name
RUN echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN useradd --no-log-init --home-dir /home/ubuntu --create-home --shell /bin/bash ubuntu && \
    adduser ubuntu sudo
RUN mkdir /work && \
    chown ubuntu: /work && \
    chmod a+rwx /work
COPY scripts /opt/pge-fw
RUN chmod +x /opt/pge-fw/bin/*
USER ubuntu 
WORKDIR /work

ENTRYPOINT ["python3", "/opt/pge-fw/fw_entrypoint.py"]


