name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]      
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2    
    - name: Build the Docker image
      run: make push
